name: quicksend
services:
  app:
    image: ${APP_IMAGE}
    container_name: quicksend_app
    env_file:
      - .env
    deploy:
      replicas: 2
      restart_policy:
        delay: 5s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
    networks:
      - default

  consumer:
    image: ${CONSUMER_IMAGE}
    container_name: quicksend_consumer
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      replicas: 6
      restart_policy:
        delay: 5s
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
    networks:
      - default

  nginx:
    image: ${NGINX_IMAGE}
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    container_name: quicksend_nginx
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  kafka:
    image: bitnami/kafka:latest
    container_name: quicksend_kafka
    environment:
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka_data:/bitnami/kafka
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  db:
    image: postgres:17
    container_name: quicksend_postgres
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local_0:redis:6379:0,local_1:redis:6379:1,local_2:redis:6379:2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  redis:
    image: redis:8.4.0
    container_name: quicksend_redis
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

  seq:
    image: datalust/seq:2025.2
    container_name: quicksend_seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINUSERNAME: "${SEQ_FIRSTRUN_ADMINUSERNAME}"
      SEQ_FIRSTRUN_ADMINPASSWORD: "${SEQ_FIRSTRUN_ADMINPASSWORD}"
    volumes:
      - seq_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - default

networks:
  default:
    driver: overlay
    attachable: true
    external: true

volumes:
  redis_data:
  postgres_data:
  seq_data:
  kafka_data:
